name: Run benchmarks

on:
  push:

jobs:
  execute_bash_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'  # Choose the Node.js version you need

      - name: Install latest effekt
        run: |
          git clone git@github.com:effekt-lang/effekt.git &&
          git checkout cbff76e875c7ce4aca5e52fd8ef170c1f66b97e9 &&
          cd effekt &&
          sbt install
        #run: |
        #  npm install -g https://github.com/effekt-lang/effekt/releases/latest/download/effekt.tgz &&
        #  npm link &&
        #  npm list -g
      - name: Execute Benchmarks
        run: |
          fasteffekt -s  